package cn.wltc.biz.system.vo;

import java.io.Serializable;
import java.util.Date;

import cn.wltc.framework.service.BaseQuery;


public class RoleQuery extends BaseQuery implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 484358246276515082L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jsdm
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jsdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jsmc
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jsms
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.pid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.px
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer px;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jszt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jszt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jssszxt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jssszxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlcjyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlxgyh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.id
     *
     * @return the value of g_xtgl_jsxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.id
     *
     * @param id the value for g_xtgl_jsxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jsdm
     *
     * @return the value of g_xtgl_jsxxb.jsdm
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJsdm() {
        return jsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jsdm
     *
     * @param jsdm the value for g_xtgl_jsxxb.jsdm
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJsdm(String jsdm) {
        this.jsdm = jsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jsmc
     *
     * @return the value of g_xtgl_jsxxb.jsmc
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJsmc() {
        return jsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jsmc
     *
     * @param jsmc the value for g_xtgl_jsxxb.jsmc
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJsmc(String jsmc) {
        this.jsmc = jsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jsms
     *
     * @return the value of g_xtgl_jsxxb.jsms
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJsms() {
        return jsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jsms
     *
     * @param jsms the value for g_xtgl_jsxxb.jsms
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJsms(String jsms) {
        this.jsms = jsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.pid
     *
     * @return the value of g_xtgl_jsxxb.pid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.pid
     *
     * @param pid the value for g_xtgl_jsxxb.pid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.px
     *
     * @return the value of g_xtgl_jsxxb.px
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.px
     *
     * @param px the value for g_xtgl_jsxxb.px
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setPx(Integer px) {
        this.px = px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jszt
     *
     * @return the value of g_xtgl_jsxxb.jszt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJszt() {
        return jszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jszt
     *
     * @param jszt the value for g_xtgl_jsxxb.jszt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJszt(String jszt) {
        this.jszt = jszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jssszxt
     *
     * @return the value of g_xtgl_jsxxb.jssszxt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJssszxt() {
        return jssszxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jssszxt
     *
     * @param jssszxt the value for g_xtgl_jsxxb.jssszxt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJssszxt(String jssszxt) {
        this.jssszxt = jssszxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jlcjsj
     *
     * @return the value of g_xtgl_jsxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlcjsj() {
        return jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jlcjsj
     *
     * @param jlcjsj the value for g_xtgl_jsxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjsj(Date jlcjsj) {
        this.jlcjsj = jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jlcjyh
     *
     * @return the value of g_xtgl_jsxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlcjyh() {
        return jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jlcjyh
     *
     * @param jlcjyh the value for g_xtgl_jsxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjyh(String jlcjyh) {
        this.jlcjyh = jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jlxgsj
     *
     * @return the value of g_xtgl_jsxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlxgsj() {
        return jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jlxgsj
     *
     * @param jlxgsj the value for g_xtgl_jsxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgsj(Date jlxgsj) {
        this.jlxgsj = jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsxxb.jlxgyh
     *
     * @return the value of g_xtgl_jsxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlxgyh() {
        return jlxgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsxxb.jlxgyh
     *
     * @param jlxgyh the value for g_xtgl_jsxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgyh(String jlxgyh) {
        this.jlxgyh = jlxgyh;
    }
}
