package cn.wltc.biz.system.model;

import java.util.Date;

import cn.wltc.common.model.BaseTreeObject;

public class SysAuthResourceInfo extends BaseTreeObject{
    /**
     * 
     */
    private static final long serialVersionUID = -446639656832006252L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.id
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzydm
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzymc
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzybz
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzybz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzytb
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzytb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzyms
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzyms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzylx
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.fid
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzydz
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzydz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.px
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private Integer px;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.qxzyzt
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String qxzyzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.jlcjsj
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private Date jlcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.jlcjyh
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String jlcjyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.jlxgsj
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private Date jlxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_qxzyxxb.jlxgyh
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    private String jlxgyh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.id
     *
     * @return the value of g_xtgl_qxzyxxb.id
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.id
     *
     * @param id the value for g_xtgl_qxzyxxb.id
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzydm
     *
     * @return the value of g_xtgl_qxzyxxb.qxzydm
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzydm() {
        return qxzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzydm
     *
     * @param qxzydm the value for g_xtgl_qxzyxxb.qxzydm
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzydm(String qxzydm) {
        this.qxzydm = qxzydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzymc
     *
     * @return the value of g_xtgl_qxzyxxb.qxzymc
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzymc() {
        return qxzymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzymc
     *
     * @param qxzymc the value for g_xtgl_qxzyxxb.qxzymc
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzymc(String qxzymc) {
        this.qxzymc = qxzymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzybz
     *
     * @return the value of g_xtgl_qxzyxxb.qxzybz
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzybz() {
        return qxzybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzybz
     *
     * @param qxzybz the value for g_xtgl_qxzyxxb.qxzybz
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzybz(String qxzybz) {
        this.qxzybz = qxzybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzytb
     *
     * @return the value of g_xtgl_qxzyxxb.qxzytb
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzytb() {
        return qxzytb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzytb
     *
     * @param qxzytb the value for g_xtgl_qxzyxxb.qxzytb
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzytb(String qxzytb) {
        this.qxzytb = qxzytb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzyms
     *
     * @return the value of g_xtgl_qxzyxxb.qxzyms
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzyms() {
        return qxzyms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzyms
     *
     * @param qxzyms the value for g_xtgl_qxzyxxb.qxzyms
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzyms(String qxzyms) {
        this.qxzyms = qxzyms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzylx
     *
     * @return the value of g_xtgl_qxzyxxb.qxzylx
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzylx() {
        return qxzylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzylx
     *
     * @param qxzylx the value for g_xtgl_qxzyxxb.qxzylx
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzylx(String qxzylx) {
        this.qxzylx = qxzylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.fid
     *
     * @return the value of g_xtgl_qxzyxxb.fid
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.fid
     *
     * @param fid the value for g_xtgl_qxzyxxb.fid
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzydz
     *
     * @return the value of g_xtgl_qxzyxxb.qxzydz
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzydz() {
        return qxzydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzydz
     *
     * @param qxzydz the value for g_xtgl_qxzyxxb.qxzydz
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzydz(String qxzydz) {
        this.qxzydz = qxzydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.px
     *
     * @return the value of g_xtgl_qxzyxxb.px
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public Integer getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.px
     *
     * @param px the value for g_xtgl_qxzyxxb.px
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setPx(Integer px) {
        this.px = px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.qxzyzt
     *
     * @return the value of g_xtgl_qxzyxxb.qxzyzt
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getQxzyzt() {
        return qxzyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.qxzyzt
     *
     * @param qxzyzt the value for g_xtgl_qxzyxxb.qxzyzt
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setQxzyzt(String qxzyzt) {
        this.qxzyzt = qxzyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.jlcjsj
     *
     * @return the value of g_xtgl_qxzyxxb.jlcjsj
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public Date getJlcjsj() {
        return jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.jlcjsj
     *
     * @param jlcjsj the value for g_xtgl_qxzyxxb.jlcjsj
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setJlcjsj(Date jlcjsj) {
        this.jlcjsj = jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.jlcjyh
     *
     * @return the value of g_xtgl_qxzyxxb.jlcjyh
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getJlcjyh() {
        return jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.jlcjyh
     *
     * @param jlcjyh the value for g_xtgl_qxzyxxb.jlcjyh
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setJlcjyh(String jlcjyh) {
        this.jlcjyh = jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.jlxgsj
     *
     * @return the value of g_xtgl_qxzyxxb.jlxgsj
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public Date getJlxgsj() {
        return jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.jlxgsj
     *
     * @param jlxgsj the value for g_xtgl_qxzyxxb.jlxgsj
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setJlxgsj(Date jlxgsj) {
        this.jlxgsj = jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_qxzyxxb.jlxgyh
     *
     * @return the value of g_xtgl_qxzyxxb.jlxgyh
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public String getJlxgyh() {
        return jlxgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_qxzyxxb.jlxgyh
     *
     * @param jlxgyh the value for g_xtgl_qxzyxxb.jlxgyh
     *
     * @mbggenerated Mon May 19 17:32:23 CST 2014
     */
    public void setJlxgyh(String jlxgyh) {
        this.jlxgyh = jlxgyh;
    }
}