package cn.wltc.biz.system.model;

import java.util.Date;

import cn.wltc.framework.service.BaseQuery;

public class SysLog extends BaseQuery {
    /**
     * 
     */
    private static final long serialVersionUID = 1154884145526482385L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.id
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.yhm
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String yhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.czlx
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String czlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.cznr
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String cznr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.czsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.ipdz
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String ipdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.mac
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.jlcjsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private Date jlcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.jlcjyh
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String jlcjyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.jlxgsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private Date jlxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_czrzb.jlxgyh
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    private String jlxgyh;
    
    private String xm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.id
     *
     * @return the value of g_xtgl_czrzb.id
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.id
     *
     * @param id the value for g_xtgl_czrzb.id
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.yhm
     *
     * @return the value of g_xtgl_czrzb.yhm
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getYhm() {
        return yhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.yhm
     *
     * @param yhdm the value for g_xtgl_czrzb.yhm
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setYhm(String yhm) {
        this.yhm = yhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.czlx
     *
     * @return the value of g_xtgl_czrzb.czlx
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getCzlx() {
        return czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.czlx
     *
     * @param czlx the value for g_xtgl_czrzb.czlx
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setCzlx(String czlx) {
        this.czlx = czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.cznr
     *
     * @return the value of g_xtgl_czrzb.cznr
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getCznr() {
        return cznr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.cznr
     *
     * @param cznr the value for g_xtgl_czrzb.cznr
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setCznr(String cznr) {
        this.cznr = cznr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.czsj
     *
     * @return the value of g_xtgl_czrzb.czsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.czsj
     *
     * @param czsj the value for g_xtgl_czrzb.czsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.ipdz
     *
     * @return the value of g_xtgl_czrzb.ipdz
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getIpdz() {
        return ipdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.ipdz
     *
     * @param ipdz the value for g_xtgl_czrzb.ipdz
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setIpdz(String ipdz) {
        this.ipdz = ipdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.mac
     *
     * @return the value of g_xtgl_czrzb.mac
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.mac
     *
     * @param mac the value for g_xtgl_czrzb.mac
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.jlcjsj
     *
     * @return the value of g_xtgl_czrzb.jlcjsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public Date getJlcjsj() {
        return jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.jlcjsj
     *
     * @param jlcjsj the value for g_xtgl_czrzb.jlcjsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setJlcjsj(Date jlcjsj) {
        this.jlcjsj = jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.jlcjyh
     *
     * @return the value of g_xtgl_czrzb.jlcjyh
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getJlcjyh() {
        return jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.jlcjyh
     *
     * @param jlcjyh the value for g_xtgl_czrzb.jlcjyh
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setJlcjyh(String jlcjyh) {
        this.jlcjyh = jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.jlxgsj
     *
     * @return the value of g_xtgl_czrzb.jlxgsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public Date getJlxgsj() {
        return jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.jlxgsj
     *
     * @param jlxgsj the value for g_xtgl_czrzb.jlxgsj
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setJlxgsj(Date jlxgsj) {
        this.jlxgsj = jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_czrzb.jlxgyh
     *
     * @return the value of g_xtgl_czrzb.jlxgyh
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public String getJlxgyh() {
        return jlxgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_czrzb.jlxgyh
     *
     * @param jlxgyh the value for g_xtgl_czrzb.jlxgyh
     *
     * @mbggenerated Mon May 12 19:29:07 CST 2014
     */
    public void setJlxgyh(String jlxgyh) {
        this.jlxgyh = jlxgyh;
    }

	public String getXm() {
		return xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}
}