package cn.wltc.biz.system.model;

import java.util.Date;

public class SysRoleAuthInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.jsid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer jsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.zyid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer zyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlcjyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_jsqxxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlxgyh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.id
     *
     * @return the value of g_xtgl_jsqxxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.id
     *
     * @param id the value for g_xtgl_jsqxxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.jsid
     *
     * @return the value of g_xtgl_jsqxxxb.jsid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getJsid() {
        return jsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.jsid
     *
     * @param jsid the value for g_xtgl_jsqxxxb.jsid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJsid(Integer jsid) {
        this.jsid = jsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.zyid
     *
     * @return the value of g_xtgl_jsqxxxb.zyid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getZyid() {
        return zyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.zyid
     *
     * @param zyid the value for g_xtgl_jsqxxxb.zyid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setZyid(Integer zyid) {
        this.zyid = zyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.jlcjsj
     *
     * @return the value of g_xtgl_jsqxxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlcjsj() {
        return jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.jlcjsj
     *
     * @param jlcjsj the value for g_xtgl_jsqxxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjsj(Date jlcjsj) {
        this.jlcjsj = jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.jlcjyh
     *
     * @return the value of g_xtgl_jsqxxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlcjyh() {
        return jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.jlcjyh
     *
     * @param jlcjyh the value for g_xtgl_jsqxxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjyh(String jlcjyh) {
        this.jlcjyh = jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.jlxgsj
     *
     * @return the value of g_xtgl_jsqxxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlxgsj() {
        return jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.jlxgsj
     *
     * @param jlxgsj the value for g_xtgl_jsqxxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgsj(Date jlxgsj) {
        this.jlxgsj = jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_jsqxxxb.jlxgyh
     *
     * @return the value of g_xtgl_jsqxxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlxgyh() {
        return jlxgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_jsqxxxb.jlxgyh
     *
     * @param jlxgyh the value for g_xtgl_jsqxxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgyh(String jlxgyh) {
        this.jlxgyh = jlxgyh;
    }
}