package cn.wltc.biz.system.model;

import java.util.Date;

public class SysUserRoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.yhid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer yhid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.jsid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer jsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlcjyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhjsxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlxgyh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.id
     *
     * @return the value of g_xtgl_yhjsxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.id
     *
     * @param id the value for g_xtgl_yhjsxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.yhid
     *
     * @return the value of g_xtgl_yhjsxxb.yhid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getYhid() {
        return yhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.yhid
     *
     * @param yhid the value for g_xtgl_yhjsxxb.yhid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setYhid(Integer yhid) {
        this.yhid = yhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.jsid
     *
     * @return the value of g_xtgl_yhjsxxb.jsid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getJsid() {
        return jsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.jsid
     *
     * @param jsid the value for g_xtgl_yhjsxxb.jsid
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJsid(Integer jsid) {
        this.jsid = jsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.jlcjsj
     *
     * @return the value of g_xtgl_yhjsxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlcjsj() {
        return jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.jlcjsj
     *
     * @param jlcjsj the value for g_xtgl_yhjsxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjsj(Date jlcjsj) {
        this.jlcjsj = jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.jlcjyh
     *
     * @return the value of g_xtgl_yhjsxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlcjyh() {
        return jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.jlcjyh
     *
     * @param jlcjyh the value for g_xtgl_yhjsxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjyh(String jlcjyh) {
        this.jlcjyh = jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.jlxgsj
     *
     * @return the value of g_xtgl_yhjsxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlxgsj() {
        return jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.jlxgsj
     *
     * @param jlxgsj the value for g_xtgl_yhjsxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgsj(Date jlxgsj) {
        this.jlxgsj = jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhjsxxb.jlxgyh
     *
     * @return the value of g_xtgl_yhjsxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlxgyh() {
        return jlxgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhjsxxb.jlxgyh
     *
     * @param jlxgyh the value for g_xtgl_yhjsxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgyh(String jlxgyh) {
        this.jlxgyh = jlxgyh;
    }
    
    ///////////////////////////////////////////
    private String jsmc;

    public String getJsmc() {
        return jsmc;
    }
    
    public void setJsmc(String jsmc) {
        this.jsmc = jsmc;
    }
    
}