package cn.wltc.biz.system.model;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

import cn.wltc.framework.service.BaseQuery;

public class SysUserInfo extends BaseQuery {
    /**
     * 
     */
    private static final long serialVersionUID = -2494099542279068168L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.yhm
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String yhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.xm
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.kl
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String kl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.yhbmdm
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String bmdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.yhzt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String yhzt = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlcjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlcjyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private Date jlxgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_xtgl_yhxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    private String jlxgyh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.id
     *
     * @return the value of g_xtgl_yhxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.id
     *
     * @param id the value for g_xtgl_yhxxb.id
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.kl
     *
     * @return the value of g_xtgl_yhxxb.kl
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getKl() {
        return kl;
    }
    
    public String getYhm() {
        return yhm;
    }
    
    public void setYhm(String yhm) {
        this.yhm = yhm;
    }

    
    public String getXm() {
        return xm;
    }

    
    public void setXm(String xm) {
        this.xm = xm;
    }

    
    public String getBmdm() {
        return bmdm;
    }

    
    public void setBmdm(String bmdm) {
        this.bmdm = bmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.kl
     *
     * @param kl the value for g_xtgl_yhxxb.kl
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setKl(String kl) {
        this.kl = kl;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.yhzt
     *
     * @return the value of g_xtgl_yhxxb.yhzt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getYhzt() {
        return yhzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.yhzt
     *
     * @param yhzt the value for g_xtgl_yhxxb.yhzt
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setYhzt(String yhzt) {
        this.yhzt = yhzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.jlcjsj
     *
     * @return the value of g_xtgl_yhxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlcjsj() {
        return jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.jlcjsj
     *
     * @param jlcjsj the value for g_xtgl_yhxxb.jlcjsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjsj(Date jlcjsj) {
        this.jlcjsj = jlcjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.jlcjyh
     *
     * @return the value of g_xtgl_yhxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlcjyh() {
        return jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.jlcjyh
     *
     * @param jlcjyh the value for g_xtgl_yhxxb.jlcjyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlcjyh(String jlcjyh) {
        this.jlcjyh = jlcjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.jlxgsj
     *
     * @return the value of g_xtgl_yhxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public Date getJlxgsj() {
        return jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.jlxgsj
     *
     * @param jlxgsj the value for g_xtgl_yhxxb.jlxgsj
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgsj(Date jlxgsj) {
        this.jlxgsj = jlxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_xtgl_yhxxb.jlxgyh
     *
     * @return the value of g_xtgl_yhxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public String getJlxgyh() {
        return jlxgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_xtgl_yhxxb.jlxgyh
     *
     * @param jlxgyh the value for g_xtgl_yhxxb.jlxgyh
     *
     * @mbggenerated Sun May 11 20:20:01 CST 2014
     */
    public void setJlxgyh(String jlxgyh) {
        this.jlxgyh = jlxgyh;
    }
    
    ///////////////////////////////////////////////////////////////////
    
    private String rememberMe;
    private List<Integer> jsids;
    private List<SysUserRoleInfo> yhjsxxb;
    private List<SysAuthResourceInfo> resourceMenuList;
//    private Collection<Role> roles;//拥有角色
//    private Collection<Permission> pmss ;//拥有权限

    
    
    public List<Integer> getJsids() {
        return jsids;
    }
    
    public List<SysAuthResourceInfo> getResourceMenuList() {
        return resourceMenuList;
    }

    public void setResourceMenuList(List<SysAuthResourceInfo> resourceMenuList) {
        this.resourceMenuList = resourceMenuList;
    }

    public void setJsids(List<Integer> jsids) {
        this.jsids = jsids;
    } 
    
    public List<SysUserRoleInfo> getYhjsxxb() {
        return yhjsxxb;
    }
    
    public void setYhjsxxb(List<SysUserRoleInfo> yhjsxxb) {
        this.yhjsxxb = yhjsxxb;
    }

    public String getRememberMe() {
        return rememberMe;
    }


    public void setRememberMe(String rememberMe) {
        this.rememberMe = rememberMe;
    }
    
    public static HashMap<String,String> yhztMaster = new HashMap<String,String>();
    static {
        
        yhztMaster.put("0", "停用");
        yhztMaster.put("1", "启用");
    }    
}